title: Diacritic
tagline: ""
url: "https://diacritic.io" # The base hostname & protocol for your site. Use it if you need absolute URL's
permalink: /blog/:title.html

github: diacritic

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "article"

sass:
  sass_dir: css/
  style: :compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
