title: Diacritic
tagline: "Changing the world, one uninspired quote at a time"
url: "https://diacritic.io" # The base hostname & protocol for your site. Use it if you need absolute URL's

github: diacritic

sass:
  sass_dir: css/
#  style: :compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
